name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Compile(win-x86)
        run: deno compile -S="homedir,uid" -N=localhost -R -W --target ${TARGET} --output=releases/obsidian-mcp-${TARGET} src/main.ts
        env:
          TARGET: x86_64-pc-windows-msvc
      - name: Compile(macos-x86)
        run: deno compile -S="homedir,uid" -N=localhost -R -W --target ${TARGET} --output=releases/obsidian-mcp-${TARGET} src/main.ts
        env:
          TARGET: x86_64-apple-darwin
      - name: Compile(macos-arm)
        run: deno compile -S="homedir,uid" -N=localhost -R -W --target ${TARGET} --output=releases/obsidian-mcp-${TARGET} src/main.ts
        env:
          TARGET: aarch64-apple-darwin
      - name: Compile(linux-x86)
        run: deno compile -S="homedir,uid" -N=localhost -R -W --target ${TARGET} --output=releases/obsidian-mcp-${TARGET} src/main.ts
        env:
          TARGET: x86_64-unknown-linux-gnu
      - name: Compile(linux-arm)
        run: deno compile -S="homedir,uid" -N=localhost -R -W --target ${TARGET} --output=releases/obsidian-mcp-${TARGET} src/main.ts
        env:
          TARGET: aarch64-unknown-linux-gnu
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: releases/obsidian-mcp-*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
